---
title: "3_EDM_Vis_MPG"
author: "Kurt Ingeman"
date: "2/10/2020"
output: html_document
---



```{r}
rm(list = ls(all.names = TRUE)) 

library(rEDM)
library(tidyr)
library(ggplot2)
library(PNWColors)

pal=pnw_palette("Shuksan2", 5, type = "discrete")
```


#multivariate model to look at interaction strengths including MPGs

```{R}

load("Data/block_data.Rdata")  

mpg <- c() 
  for(stk in 1:length(block_data)) { 
      mpg[stk] <- block_data[[stk]]$mpg[1]
  } 

target_var <- "rec4_n" #the focal variable of the analysis


# testvar <- c("harv_n","up48.apr.2", "up48.may.2", "pdo.may.2", "pdo.win.2", "up48.oct.2", "up48.nov.2", "npgo.yr.2", "hatch.spring.2", "pinn.CSLmales.4", "pinn.CSLbonn.4","pinn.SSLaerial.4", "SRKW.Lpod.4", "SRKW.JKLpods.5", "flow.gageht.4")

testvar <- c("pinn.CSLhaulout.4", "pinn.CSLbonn.4","pinn.SSLaerial.4", "pinn.SSLbonn.4", "pinn.HSaerial.4", "pinn.HSbonn.4")

  
for(u in c(1,3,4,5)){ #1,3,4,5 For each MPG excluding lower Snake for which there is only one stock
    data <- block_data[c(mpg==u)]
    mpgname <- as.character(data[[1]]$mpg[1])

     # concatenate the time series of the different stocks in the MPG together
    keys <-c(names(data[[1]]))
    merged_data <-setNames(do.call(mapply, c(FUN=c, lapply(data, `[`, keys))), keys)
    merged_data <- as.data.frame(merged_data)
    valid <-  is.finite(merged_data$rec4_n) & is.finite(merged_data$eff_n) 
    block <- merged_data[valid,]  
    
    # list the begin and end points of each stock and the break points within stocks
    lib <- matrix(NA, nrow = length(which(diff(block$year)!=1))+1, ncol = 2)
            lib[,1] <- c(1, which(diff(block$year)!=1)+1)
            lib[,2] <- c(which(diff(block$year)!=1), nrow(block))
            #only keep libraries with sufficient length
            validlib <- lib[,2]-lib[,1]
            predlib <- lib[validlib>3,]
    
    #Only keep data contained within the libraries with sufficient length
    keepvec <- matrix(FALSE,nrow=length(block), ncol=1)
    for(j in 1: NROW(predlib)){
    keepvec[predlib[j,1]:predlib[j,2]] <- TRUE
      }
    block <- block[keepvec,]
    rownames(block) <- NULL #remove rownames
     
     lib <- matrix(NA, nrow = length(which(diff(block$year)!=1))+1, ncol = 2)
            lib[,1] <- c(1, which(diff(block$year)!=1)+1)
            lib[,2] <- c(which(diff(block$year)!=1), nrow(block))
            
    # determine the best univariate embedding dimension and theta for the target variable (total recruitment)        
          data_target <- as.matrix(cbind(block$year, block[target_var], block$eff_n))
          rownames(data_target) <- NULL #remove rownames to supress error in CCM: NAs introduced by coersion
          simplex_output <- simplex(data_target, lib=lib, pred=lib,  E = 1:8, silent = TRUE)
          best_E<- min(simplex_output$E[simplex_output$rho>max(simplex_output$rho)-sd(simplex_output$rho)]) #choose the smallest E whose rho is within 1 stdv of the maximum rho)
          smap_output <- s_map(data_target, lib=lib, pred=lib, E=best_E) 
          best_T <- smap_output$theta[which.max(smap_output$rho)] 
  
           #for each of the hatchery variables  
 testvar <- testvar
 smapcoeffs = list()
 for(i in 1:length(testvar)){          
#Perform multivariate forecasts
   # for each embedding, use smaps to calculate the coefficients over time
         
            MultiEDM_data <- as.matrix(cbind(block["year"], block[target_var], block["eff_n"], block[testvar[i]]))
            rownames( MultiEDM_data) <- NULL #remove rownames to supress error in CCM: NAs introduced by coersion
            smap <- block_lnlp(MultiEDM_data, lib=lib, pred=lib, method = c("s-map"), columns = c(target_var, "eff_n", testvar[i]), theta = best_T, first_column_time = TRUE, save_smap_coefficients = TRUE)
            #smap <- block_lnlp(MultiEDM_data[,2:4], lib=lib, pred=lib, method = c("s-map"), columns = c(target_var, "eff_n", testvar[i]), theta = best_T, first_column_time = FALSE, save_smap_coefficients = TRUE)
           
                  a <- data.frame(smap[[1]]$smap_coefficients)
                  colnames(a) <- paste(i, c(colnames(MultiEDM_data[,2:4]),"constant"))
                  smapcoeffs[[i]] <- a
                   
 }
 
 
            #convert large smap coefficients list into plottable data frame
            d = do.call(cbind, smapcoeffs)  
            d <- cbind(block$year, d)
            colnames(d)[1] <- c("yr")
            d <- gather(d, key, coeff, -yr)  #create long data for plotting
            d <- separate(d, key, into=c("model","var"), sep = " ")  #add columns for model number, variable
            d <- d %>% filter(!grepl('constant', var))  #remove coefficients for constants
            # rename some of the variables
            d$var <- gsub('rec4_n', 'rec4', d$var) 
            d$var <- gsub("eff_n", 'eff', d$var)
            d$var <- gsub("pinn.CSLhaulout.4", "pinn.CSL.aerial.4", d$var)
            d$var <- gsub("pinn.CSLbonn.4", "pinn.CSL.bonn.4", d$var)
            d$var <- gsub("pinn.SSLaerial.4", "pinn.SSL.aerial.4", d$var)
            d$var <- gsub("pinn.SSLbonn.4", "pinn.SSL.bonn.4", d$var)
            d$var <- gsub("pinn.HSaerial.4", "pinn.HS.aerial.4",d$var)
            d$var <- gsub("pinn.HSbonn.4", "pinn.HS.bonn.4", d$var)
            
             d <- separate(d, var, into=c("var","spp","scale", "offset"), extra = "merge", sep = "\\.")  
            d$offset <- d$offset %>% replace_na(0) #replace NAs for the target variable and offset values
            str(d)
 
#how do variables affect recruitment of wild salmon 
#            df <- d %>% filter(!var %in% c("eff", "rec4"))
            
write.csv(d, paste("~/Github/Coordinated-Recoveries-GitHub/CORE EDM visual/Data/IS_pinn_in_", mpgname, "MPG.csv", sep = ""))
            
            
}
 



```


```{r}

# Call in separate MPG CCM output 

IM <- read.csv("~/Github/Coordinated-Recoveries-GitHub/CORE EDM visual/Data/IS_pinn_inImnahaMPG.csv")

MF <- read.csv("~/Github/Coordinated-Recoveries-GitHub/CORE EDM visual/Data/IS_pinn_inMiddle Fork SalmonMPG.csv")

SF <- read.csv("~/Github/Coordinated-Recoveries-GitHub/CORE EDM visual/Data/IS_pinn_inSouth Fork SalmonMPG.csv")

UP <- read.csv("~/Github/Coordinated-Recoveries-GitHub/CORE EDM visual/Data/IS_pinn_inUpper SalmonMPG.csv")

# Give a variable for subbasin

IM$mpg <- "IM"
MF$mpg <- "MF"
SF$mpg <- "SF"
UP$mpg <- "UP"

# bind rows
pinn <- rbind.data.frame(IM, MF, SF, UP)

```


```{r}

# plot with facets by MPG

pal.3 = pnw_palette("Shuksan2", 3, type = "discrete")
pal.5 = pnw_palette("Shuksan2", 5, type = "discrete")

pinn <- pinn %>% filter(!is.na(spp)) 

p5 <- ggplot(pinn, aes(x=spp, y=coeff, fill=spp)) + 
  geom_violin(trim = FALSE) +
  scale_fill_manual(values = pal.3) +
  geom_hline(yintercept = 0,  linetype="dashed") +
    facet_wrap(~mpg, nrow = 1)
  
  


p6 <- ggplot(pinn, aes(x=spp, y=coeff, fill=spp)) + 
  geom_violin(trim = FALSE) +
  facet_wrap(~mpg, nrow = 1) 


```

