---
title: "6_Vis_Ridgeline"
author: "Kurt Ingeman"
date: "3/30/2020"
output: html_document
---

```{r}

library(ggridges)
library(ggplot2)
library(viridis)
library(PNWColors)
library(hrbrthemes)
library(dplyr)
library(forcats)

```

```{r}

load("Data/block_data.Rdata")

dat <- do.call("rbind", block_data) %>% 
  mutate(spawn_log = log(spawn_nat  + 1)) %>% 
  group_by(stk) %>% 
  mutate(mean_log = mean(na.omit(spawn_log))) %>% 
  ungroup()



```


# Plot
```{r}

pal=pnw_palette("Shuksan2",5, type = "discrete")

dat$mpg <- factor(dat$mpg, levels = c("Lower Snake", "Imnaha", "South Fork Salmon", "Middle Fork Salmon", "Upper Salmon"))

ggplot(dat, aes(x = spawn_log, y = fct_reorder(stk, mean_log, mean, .desc = TRUE), fill = mpg)) +
  geom_density_ridges(scale = 7, alpha = .8) +
  labs(title = 'Natural Spawning (time-averaged)') +
  scale_fill_manual(values = rev(pal)) +
  theme_ridges() +
    theme(
      axis.text.y = element_blank(),
      legend.position="none",
      panel.spacing = unit(1, "inches"),
      strip.text.x = element_text(size = 2)
    ) + 
  facet_grid(cols = vars(mpg))

dat <- dat %>% 
  filter(!mpg == "Lower Snake")

dat$mpg <- factor(dat$mpg, levels = c("Imnaha", "South Fork Salmon", "Middle Fork Salmon", "Upper Salmon"))

p <- ggplot(dat, aes(x = spawn_nat, y = factor(year), fill = mpg)) +
  geom_density_ridges(scale = 7, alpha = 1) +
  labs(title = 'Natural Spawning (time-averaged)') +
  scale_fill_manual(values = rev(pal)) +
  theme_ridges(center_axis_labels = T) +
  theme(
      axis.text.y = element_blank(),
      axis.text.x = element_blank(),
      legend.position="none",
      panel.spacing = unit(.1, "lines"),
      strip.text.x = element_text(size = 8)
    ) +
  labs(y = "Year") +
  facet_grid(cols = vars(mpg))

ggsave(filename =         
 "Figs/Manuscript/FigZ.pdf", plot = p, width = 9, height = 6, units = "in") 


```



