---
title: "CORE EDM Analysis"
author: "Alison Iles"
date: "6/3/2019"
output:  pdf_document: default
          html_document
          keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load the necessary packages. 
Note that the `echo = FALSE` parameter prevents printing of the R code.

```{r, echo=FALSE}
library(rEDM)
#library(rjags)
library(reshape2)
library(rgl)
library(ggplot2)
library(gridExtra)
library(xtable)
```

#load data

```{R}
folder <- "/Users/alisoniles/Google Drive/Coordinated Recoveries/CORE_EDM/Data/analysis ready/"      # path to folder that holds data in .csv files
data <- read.csv(paste(folder, "SRSS_cohort_prelim.csv", sep=''))
```

#normalize

```{R}
 # To focus on one stock to figure out what's going on
stock_df <- subset(data, stk == "Bear Valley Creek") 
 
# The original code normalized by cycle line. Chinook don't demonstrate a strong cycle line, so I changed the normalize_by_cycle_line function to normalize on a 1 year cycle 
    normalize_by_cycle_line <- function(ts)
{
    n <- length(ts)
    means <- rep.int(NA, times = 4) #replicate NA 4 times
    sds <- rep.int(NA, times = 4)
    mu <- rep.int(NA, times = n)
    sigma <- rep.int(NA, times = n)
    for(k in 1:1) #for each cycle line (every 4 years the population cycles in sockeye, I've changed it to 1 because there are no cycle lines for chinook)
    {
        index <- seq(from = k, to = n, by = 1) #changed by=4 to b=1.
        means[k] <- mean(ts[index], na.rm = TRUE) #mean of every 4th element of the time series
        sds[k] <- sd(ts[index], na.rm = TRUE) #standard dev.
        mu[index] <- means[k]
        sigma[index] <- sds[k]
    }
    ts <- (ts - mu) / sigma  #normalize by cycle line
    df <- data.frame(cbind(ts, mu, sigma))
    return(df)
    }
    
     preprocess_stock <- function(stock_df)
    {
        n <- NROW(stock_df)  #n is the number of observations for the stock
         
        stock_df$ret <- stock_df$rec3 + c(NA, stock_df$rec4[1:(n-1)]) + c(NA, NA, stock_df$rec5[1:(n-2)]) #+ c(NA, NA, NA, stock_df$rec6[1:(n-3)]) # age-3,4,5,and 6 fish (aligned to rec3) #total returns are calculated by adding 3 year old recruits plus 4 year old recruits from the previous brood year, plus 5 year olds from two years prior...etc. This value is aligned to the rec3 brood year, not the year they are actually returning together. 
       
# Normalize on a 1 year cycle line (i.e. NO cycle line!)
        
        temp <- normalize_by_cycle_line(stock_df$eff)
        stock_df$eff_n <- temp$ts #normalized number of effective spawners
        stock_df$eff_mu <- temp$mu
        stock_df$eff_sigma <- temp$sigma
        
        temp <- normalize_by_cycle_line(stock_df$rec3)
        stock_df$rec3_n <- temp$ts #normalized 4 year old recruits
        stock_df$rec3_mu <- temp$mu
        stock_df$rec3_sigma <- temp$sigma
        
        temp <- normalize_by_cycle_line(stock_df$rec4)
        stock_df$rec4_n <- temp$ts #normalized 4 year old recruits
        stock_df$rec4_mu <- temp$mu
        stock_df$rec4_sigma <- temp$sigma

        temp <- normalize_by_cycle_line(stock_df$rec5)
        stock_df$rec5_n <- temp$ts #normalized 5 year old recruits
        stock_df$rec5_mu <- temp$mu
        stock_df$rec5_sigma <- temp$sigma
        
        temp <- normalize_by_cycle_line(stock_df$rec)
        stock_df$rec_n <- temp$ts #normalized total recruits
        stock_df$rec_mu <- temp$mu
        stock_df$rec_sigma <- temp$sigma

        return(stock_df)
    }   

     
# filter stocks we don't want
stock_data <- split(data, data$stk)    
stock_data <- lapply(stock_data, preprocess_stock) 
# lapply returns a list of the same length as X, each element of which is the result of applying FUN to the corresponding element of X.
```

#Figure out how to concatenate the data and run univariate EDM on just the recruit data...


#load environmental data

```{R}
env_data <- read.csv(paste(folder, "SRSS_env_prelim.csv", sep=''))

make_block <- function(stock_df, env_data)
    {
        pdo_names <- "PDO_win"
        upwelling_names <- c("up_apr", "up_oct", "up_nov")
        pdo <- normalize(env_data[, pdo_names])
        upwelling <- normalize(env_data[, upwelling_names])
        
        # line up environmental data
        # lag temperature and river upwelling 2 years
        desired_years <- stock_df$yr + 2  #brood year + 2 
        index_in_env_data <- match(desired_years, env_data$year)
        index_in_stock_df <- 1:length(desired_years)
        
        upwelling_cols <- data.frame(matrix(NA, nrow = length(desired_years), ncol = NCOL(upwelling)))
        upwelling_cols[index_in_stock_df,] <- upwelling[index_in_env_data, ]
        stock_df[, upwelling_names] <- upwelling_cols
        
        # lag PDO by 2 years 
        desired_years <- stock_df$yr + 2
        index_in_env_data <- match(desired_years, env_data$year)
        pdo_cols <- data.frame(matrix(NA, nrow = length(desired_years), ncol = 1))
        pdo_cols[index_in_stock_df,] <- pdo[index_in_env_data]
        stock_df[, pdo_names] <- pdo_cols
        
        return(stock_df)
    }

block_data <- lapply(stock_data, function(stock_df) { make_block(stock_df, env_data)})
    

    # save and return
    save(block_data, file = "block_data.Rdata")
    return()

```

